name: linux C++ CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: mkdir cmake-build-debug && cd cmake-build-debug && cmake .. && make install
